About:
  aliases:
    - credits
  text: >
    An Eclipse Phase RPG AvLI muse meshed through Discord. Eclipse Phase is
    published by Posthuman Studios. See https://eclipsephase.com/ .

    The source code for OpenMuse can be found at https://github.com/swdevlin/muse
