about:
  title: About
  aliases:
    - credits
  text: >
    An Traveller RPG library bot, networked through Discord. Traveller is
    published by Far Future Enterprises. See https://www.farfuture.net/ .

    The source code for OpenMuse can be found at https://github.com/swdevlin/muse
