# Generated by Django 3.2.8 on 2021-10-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0002_server_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='icon',
            field=models.TextField(null=True),
        ),
    ]
