# Generated by Django 3.2.8 on 2021-10-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0003_server_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='owner_id',
            field=models.TextField(null=True),
        ),
    ]
