# Generated by Django 3.2.8 on 2021-10-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0004_server_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='discord_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('server', 'title')},
        ),
    ]
