# Generated by Django 3.2.8 on 2021-10-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0006_auto_20211013_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='references',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
