# Generated by Django 3.2.8 on 2021-10-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0007_auto_20211013_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='references',
            new_name='alias_for',
        ),
    ]
