# Generated by Django 3.2.8 on 2021-10-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0008_rename_references_topic_alias_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.TextField(null=True),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['server', 'parent'], include=('text',), name='parent_lookup'),
        ),
    ]
