# Generated by Django 3.2.8 on 2021-10-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0010_auto_20211014_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='page',
            field=models.TextField(null=True),
        ),
    ]
