# Generated by Django 3.2.8 on 2021-10-16 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muse', '0011_topic_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='admins',
            field=models.ManyToManyField(related_name='servers', to=settings.AUTH_USER_MODEL),
        ),
    ]
