# Generated by Django 3.2.8 on 2021-11-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0014_server_wiki_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
