# Generated by Django 3.2.8 on 2021-12-03 22:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0015_auto_20211122_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignJobsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_error', models.TextField(null=True)),
                ('results', models.TextField(null=True)),
                ('filename', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muse.server')),
            ],
            options={
                'db_table': 'campaign_jobs',
            },
        ),
    ]
