# Generated by Django 3.2.8 on 2021-12-27 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0016_campaignjobslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('prefix', models.TextField(default='muse')),
                ('icon', models.TextField(null=True)),
                ('wiki_url', models.URLField(null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muse.server')),
            ],
            options={
                'db_table': 'channel',
            },
        ),
    ]
