# Generated by Django 3.2.8 on 2021-12-27 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0017_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='modified',
        ),
        migrations.CreateModel(
            name='ChannelTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('key', models.TextField()),
                ('text', models.TextField(null=True)),
                ('alias_for', models.TextField(null=True)),
                ('parent', models.TextField(null=True)),
                ('page', models.TextField(null=True)),
                ('wiki_slug', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('category', models.TextField(null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muse.server')),
            ],
            options={
                'db_table': 'channel_topic',
            },
        ),
        migrations.AddIndex(
            model_name='channeltopic',
            index=models.Index(fields=['channel', 'parent'], include=('title',), name='channel_parent_lookup'),
        ),
        migrations.AddIndex(
            model_name='channeltopic',
            index=models.Index(fields=['channel', 'key'], name='channel_topic_key'),
        ),
        migrations.AlterUniqueTogether(
            name='channeltopic',
            unique_together={('channel', 'key')},
        ),
    ]
