# Generated by Django 3.2.8 on 2021-12-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0020_channel_personality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='prefix',
        ),
    ]
