# Generated by Django 3.2.8 on 2021-12-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muse', '0023_auto_20211227_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='wiki_url',
        ),
    ]
