About:
  aliases:
    - credits
  text: >
    Mongoose Traveller 2022 is produced by Mongoose Publishing https://www.mongoosepublishing.com .
    
    
    Traveller is a trademark of Far Future Enterprises https://www.farfuture.net/ .


    The source code for OpenMuse can be found at https://github.com/swdevlin/muse
