# Generated by Django 3.2.8 on 2021-10-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211016_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='discriminator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='locale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='username',
            field=models.TextField(unique=True),
        ),
    ]
