# Generated by Django 3.2.8 on 2021-10-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211018_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='personality',
            field=models.TextField(default='default'),
        ),
    ]
