About:
  aliases:
    - credits
  text: >
    The Call of Cthulhu persona references *Call of Cthulhu, 7th Edition*, by Sandy Petersen and published by Chaosium Inc.
    See https://www.chaosium.com/call-of-cthulhu-rpg/ .


    The source code for OpenMuse can be found at https://github.com/swdevlin/muse
